version: "3"
services:
  postgresdb:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cardb
  api:
    build:
      dockerfile: Dockerfile
      context: ./back
    volumes:
      - ./back:/app
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - 3000:3000
